---
all:
  children:
    group1:
      hosts:
        hostA:
          ansible_host: localhost
          ansible_connection: local
    group2:
      hosts:
        hostB:
          ansible_host: localhost
          ansible_connection: local
    group3:
      hosts:
        hostC:
          ansible_host: localhost
          ansible_connection: local
